import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Level 1 — 40,000ft: Vision & Philosophy
  visionSidebar: [{type: 'autogenerated', dirName: 'vision'}],

  // Level 2 — 20,000ft: Ecosystem Blueprint
  blueprintSidebar: [{type: 'autogenerated', dirName: 'blueprint'}],

  // Level 3 — 10,000ft: Entities & Platforms
  entitiesSidebar: [{type: 'autogenerated', dirName: 'entities'}],

  // Level 4 — 5,000ft: Systems & Modules
  systemsSidebar: [{type: 'autogenerated', dirName: 'systems'}],

  // Level 5 — 1,000ft: Products, Revenue & Markets
  productsSidebar: [{type: 'autogenerated', dirName: 'products'}],

  // Level 6 — Ground Level: Execution & Operations
  executionSidebar: [{type: 'autogenerated', dirName: 'execution'}],

  // Level 7 — Microscopic: Technical Architecture
  architectureSidebar: [{type: 'autogenerated', dirName: 'architecture'}],

  // Level 8 — Substrate: Knowledge Foundation
  knowledgeSidebar: [{type: 'autogenerated', dirName: 'knowledge'}],

  // SOPs, BPMNs & Operational Workflows
  processesSidebar: [{type: 'autogenerated', dirName: 'processes'}],

  // Visual Guides, Maps & Reading Paths
  guidesSidebar: [{type: 'autogenerated', dirName: 'guides'}],
};

export default sidebars;
